name: Hugging Face Sync

on:
  repository_dispatch:
    types: [huggingface-sync]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log success message
        run: echo "Successfully received webhook from Hugging Face"
