name: Hugging Face Sync

on:
  push:  # main 브랜치에 푸시될 때 트리거
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Optional: Run tests or build
        run: |
          echo "Running tests or other tasks..."
