name: Hugging Face Sync

on:
  repository_dispatch:
    types: [huggingface-sync]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes
        env:
          TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name "qqwaseoke"
          git config --global user.email "qqwaseoke@gmail.com"
          git pull origin main
