name: Hugging Face Update Trigger

on:
  repository_dispatch:
    types: [huggingface_update]

jobs:
  process-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Event Information
        run: echo "Triggered by Hugging Face update event."
