name: Hugging Face Sync

on:
  schedule:
    - cron: '0 * * * *'  # 매 정각마다 실행
  workflow_dispatch:  # 수동으로 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone Hugging Face Space
        run: |
          git clone https://huggingface.co/spaces/waseoke/shortpingoo.git
          cp -r shortpingoo/* .
      
      - name: Commit and Push changes
        run: |
          git config --global user.name "qqwaseoke"
          git config --global user.email "qqwaseoke@gmail.com"
          git add .
          git commit -m "RF-184 Update Two-Tower Model" || echo "Nothing to commit"
          git push origin main
